// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScript(arg1) {
  return window['go']['main']['App']['AddScript'](arg1);
}

export function DeleteScript(arg1) {
  return window['go']['main']['App']['DeleteScript'](arg1);
}

export function DisableStartup() {
  return window['go']['main']['App']['DisableStartup']();
}

export function EnableStartup() {
  return window['go']['main']['App']['EnableStartup']();
}

export function GetScripts() {
  return window['go']['main']['App']['GetScripts']();
}

export function GetStartupStatus() {
  return window['go']['main']['App']['GetStartupStatus']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function RunScript(arg1) {
  return window['go']['main']['App']['RunScript'](arg1);
}

export function SetLocale(arg1) {
  return window['go']['main']['App']['SetLocale'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function ToggleScript(arg1, arg2) {
  return window['go']['main']['App']['ToggleScript'](arg1, arg2);
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}

export function UpdateScript(arg1, arg2) {
  return window['go']['main']['App']['UpdateScript'](arg1, arg2);
}
