// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddScript(arg1:main.ScriptInput):Promise<Array<main.Script>>;

export function DeleteScript(arg1:string):Promise<Array<main.Script>>;

export function DisableStartup():Promise<main.StartupStatus>;

export function EnableStartup():Promise<main.StartupStatus>;

export function GetScriptRunningStatus():Promise<Array<main.ScriptRunningStatus>>;

export function GetScripts():Promise<Array<main.Script>>;

export function GetStartupStatus():Promise<main.StartupStatus>;

export function HideWindow():Promise<void>;

export function IsWindowVisible():Promise<boolean>;

export function PickScriptPath():Promise<string>;

export function Quit():Promise<void>;

export function RunScript(arg1:string):Promise<void>;

export function SetLocale(arg1:string):Promise<void>;

export function ShowWindow():Promise<void>;

export function ToggleScript(arg1:string,arg2:boolean):Promise<Array<main.Script>>;

export function ToggleWindow():Promise<void>;

export function UpdateScript(arg1:string,arg2:main.ScriptInput):Promise<Array<main.Script>>;
